spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/test
        username: root
        password: 1234
        hikari:
            auto-commit: true
            connection-test-query: SELECT 1
            maximum-pool-size: 5
    jpa:
        show_sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
